version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
        - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
        - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
    ports:
      - "3000:3000"
    env_file:
      - .env
